spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:certs/public.pem

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem