spring:
  datasource:
    url: jdbc:postgresql://dpg-d37bib3e5dus7397jmv0-a.frankfurt-postgres.render.com:5432/my_database_1m3o?sslmode=require
    username: my_database_1m3o_user
    password: m52a7N9kMspBoUmFOMSbU9cRy1wSQvhe
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true