spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:certs/public.pem
sentry:
  dsn: https://9aa7f8d08d8ade0c17a6edab60a05670@o4510108694282240.ingest.de.sentry.io/4510108699197520
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem